thing = "HELLO world HERE is SOME text"
print(thing.lower())
print(thing.upper())
print(thing.isdigit())
locworld = thing.find("world")
print(locworld)
print(thing[::-1])
print("Is palindrome?", thing == thing[::-1])
print(thing.split(' '))
print("Hello " * 5)